version: '3.7'

services:

  app:
    build: .
    command: sh -c "npm start"
    ports:
      - 4200:4200
    volumes:
      - ./app/:/home/node/app
      - ./app/node_modules:/home/node/app/node_modules

volumes:
  node_modules:

